WebsiteTemplateIntegration::Application.routes.draw do
  get 'website_template/index'
  get 'website_template/attractions'
  get 'website_template/aboutus'
  get 'website_template/gallery'
  get 'website_template/blog'
  get 'website_template/rooms'
  get 'website_template/contact-us' => 'website_template#contact'
  get 'website_template/room-details' => 'website_template#roomDetails'
  get 'website_template/modify-booking' => 'website_template#modifyBooking'
  get 'website_template/terms-conditions' => 'website_template#termsConditions'
  get 'website_template/sitemap'
  get 'website_template/cancelled-confirm' => 'website_template#cancelledConfirm'
  get 'website_template/cancelled-booking' => 'website_template#cancelledBooking'
  get 'website_template/booking-details' => 'website_template#bookingDetails'
  get 'website_template/thankyou'
  get 'website_template/getdata'
  get 'website_template/search-result' => 'website_template#searchResult'
end
